import express from 'express';
import authToken from '../../middleware/auth/auth.middle';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { AttendanceValidationSchema } from '../../utils/validators.impl';
import createEmployeeAttendance from '../../service/impl/attendance/createEmployeeAttendance/createEmployeeAttendance';
import showEmployeeAttendances from '../../service/impl/attendance/showEmployeeAttendances/showEmployeeAttendances';
const router = express.Router();
router.post('/create-attendance', authToken, globalValidator(AttendanceValidationSchema), createEmployeeAttendance);
router.get('/show-employee-attendances', authToken, showEmployeeAttendances);
export default router;