import express from 'express';
import authToken from '../../middleware/auth/auth.middle';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { employeeSchema, updateEmployeeSchema } from '../../utils/validators.impl';
import createEmployee from '../../service/impl/employee/createEmployee/createEmployee.impl';
import showEmployees from '../../service/impl/employee/showEmployees/showEmployees.impl';
import showEmployee from '../../service/impl/employee/showEmployee/showEmployee.impl';
import updateEmployee from '../../service/impl/employee/updateEmployee/updateEmployee.impl';
const router = express.Router();
router.post('/create-employee', authToken, globalValidator(employeeSchema), createEmployee);
router.get('/show-employees', authToken, showEmployees);
router.get('/show-employee/:id', authToken, showEmployee);
router.put('/update-employee/:id', authToken, globalValidator(updateEmployeeSchema), updateEmployee);
export default router;