import express from 'express';
import authToken from '../../middleware/auth/auth.middle';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { employeeSchema } from '../../utils/validators.impl';
import createEmployee from '../../service/impl/employee/createEmployee/createEmployee.impl';
import showEmployees from '../../service/impl/employee/showEmployees/showEmployees.impl';
const router = express.Router();
router.post('/create-employee', authToken, globalValidator(employeeSchema), createEmployee);
router.get('/show-employees', authToken, showEmployees);
export default router;