import express from 'express';
import authToken from '../../middleware/auth/auth.middle';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { documentManagementValidationSchema } from '../../utils/validators.impl';
import createAndUploadDocument from '../../service/impl/document/uploadDocument/uploadDocument';
import showUploadedDocuments from '../../service/impl/document/showDocuments/showDocuments';
const router = express.Router();
router.post('/submit-employee-documents', authToken, globalValidator(documentManagementValidationSchema), createAndUploadDocument);
router.get('/show-submitted-employee-documents', authToken, showUploadedDocuments);
export default router;