import express from 'express';
import authToken from '../../middleware/auth/auth.middle';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { trainingValidationSchema } from '../../utils/validators.impl';
import createTrainingSession from '../../service/impl/training/createTrainingSession/createTrainingSession';
import showTrainingSessions from '../../service/impl/training/showTrainingSessions/showTrainingSessions';
import showTrainingSession from '../../service/impl/training/showTrainingSession/showTrainingSession';
const router = express.Router();
router.post('/create-training-session', authToken, globalValidator(trainingValidationSchema), createTrainingSession);
router.get('/show-training-session', authToken, showTrainingSessions);
router.get('/show-training-session/:id', authToken, showTrainingSession);
export default router;